### ISSUE TITLE
enable_shared_from.hpp not found

### ISSUE THREAD

**Issue by benstadin** [vinniefalco/BeastLounge#20]
Having Boost 1.70 installed, the following include cannot be found:

`#include <boost/smart_ptr/enable_shared_from.hpp>`

**Comment by benstadin** [comment]
Seems new in 1.71. Didn't guess that at first, since the project was updated months before 1.71 was released. nevertheless, have to stick to 1.70 for the moment.

**Comment by vinniefalco** [comment]
Peter Dimov's improvements to Boost.SmartPtr (in 1.71) are very exciting!

**Comment by benstadin** [comment]
Good to know. I'll revisit it once 1.71 is available via brew.
