### ISSUE TITLE
64-bit OpenSSL doesn't work with the cmake script

### ISSUE THREAD

**Issue by vinniefalco** [vinniefalco/BeastLounge#23]
The CMakeLists.txt needs to know how to select the correct lib for both 32 and 64 bit arch.

**Comment by madmongo1** [comment]
Windows, Linux or OS X?

**Comment by madmongo1** [comment]
Like all cmake packages, hint variables can be set to help cmake find the correct library if not installed in a standard place for the build host.

###Hints:
Set `OPENSSL_ROOT_DIR` to the root directory of an OpenSSL installation. 
Set `OPENSSL_USE_STATIC_LIBS` to `TRUE` to look for static libraries. 
Set `OPENSSL_MSVC_STATIC_RT` set `TRUE` to choose the MT version of the lib.

Ref: https://cmake.org/cmake/help/latest/module/FindOpenSSL.html

Are you able to supply some "steps to reproduce"? i.e. which libraries installed/built where in the file system?

**Comment by vinniefalco** [comment]
Windows. I build a Visual Studio solution and then build that. Stock OpenSSL Windows installer (both 32 and 64 bit installed).

**Comment by vinniefalco** [comment]
Using vcpkg to install 32 and 64 bit OpenSSL, and then using the vcpkg toolchain file, fixes this.
